# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['me@example.com']

    # adding regular expression - all emails will be sent to delivery_address instead of delivery_whitelists domain
    delivery_whitelists:
      - '/@special\.com$/'
